### ISSUE TITLE
Chapter 6: Broken Vagrant script with chef_solo provision failure

### ISSUE THREAD

**Issue by gauravguptaster** [semmypurewal/LearningWebAppDev#78] opened 2016-07-27 10:21 UTC
Current version of Vagrant 1.8.5 (on Virtualbox 5.1) throws the following error when provisioning (Ubuntu Precise):

==> default: Running provisioner: chef_solo...
    default: Installing Chef (latest)...
Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

As far as I could track down the issue seems to with identification of the guest OS as linux instead of Ubuntu.

**Comment by samirgandhi19** [comment] 2016-08-01 19:19
I am having the same issue, I do not understand the environments enough to find a solution.

**Comment by semmypurewal** [comment] 2016-08-01 23:11
Thanks for reporting this! Can you both give me a few more details? For example, what is your host operating system, and what version is it?

**Comment by semmypurewal** [comment] 2016-08-01 23:20
Also, can you try installing an older version of Vagrant and/or VirtualBox to see if the issue goes away? That might help us narrow it down.

**Comment by gauravguptaster** [comment] 2016-08-02 04:38
I am running Mac OS X El Capitan 10.11.5, Vagrant 1.8.5 and Virtual Box 5.1. However, there are more issues with Ubuntu Precise. It is out of LTS and the biggest issue is that NPM doesn't work at all as it can't even connect to its registry. Directly updating it via apt-get doesn't work and I had to use another method to completely remove and update to the newest version. Trying to install older versions of Vagrant and Virtual Box will not work because of updates to chef_solo and npm. I recommend upgrading the script for Ubuntu 16.04 LTS. Everything will work as before apart from Express 4 (but then you can always also install Express 3 where needed).

**Comment by semmypurewal** [comment] 2016-08-02 14:10
Thanks, @gauravguptaster. Have you gotten it working by updating the Vagrant configuration? You'll just need to change the `config.vm.box` entry in the Vagrantfile. If you've gotten it to work, let me know and I'll give it a try ASAP.

I'm surprised NPM won't work, b/c I think chef is installing Node.js as a binary from the Node.js download sites, not via apt-get. So it shouldn't be affected by the version of linux.

I probably won't have time to look at this in detail for several days. But if you can get it working and set up a PR, that would be super-helpful! Otherwise, I'll follow up soon.

**Comment by samirgandhi19** [comment] 2016-08-02 15:46
I am running OSX El Capitan 10.11.16, vagrant 1.8.5, VirtualBox 5.0.16. I am having the same issue that NPM will not connect to the registry. 

> I'm surprised NPM won't work, b/c I think chef is installing Node.js as a binary from the Node.js download sites, not via apt-get. So it shouldn't be affected by the version of linux.

Would the issue then be going back to the initial problem that the chef_install was not allowed by the guest OS? 

Here is my NPM error:

```
vagrant@precise32:~/app/Express$ npm install express@3
npm http GET https://registry.npmjs.org/express

npm ERR! Error: failed to fetch from registry: express
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
```

**Comment by semmypurewal** [comment] 2016-08-03 15:20
This looks like an issue with Vagrant 1.8.5. I was able to successfully get chef_solo installed and my app running using Vagrant 1.8.4 and VirtualBox 5.0 (Vagrant 1.8.4 is not compatible with VBox 5.1). You can download Vagrant 1.8.4 here:

https://releases.hashicorp.com/vagrant/1.8.4/

I'll need to do some digging to understand the problem with Vagrant 1.8.5.

I also discovered that there's an error when the coudfoundry client is installed. This won't affect Chapter 6/7, though, so you should be able to continue working through those while I'm troubleshooting the issue.

Please let me know if this doesn't work for you!! Thanks!

**Comment by semmypurewal** [comment] 2016-08-03 15:24
Also, I wasn't able to reproduce the NPM issue once I successfully got chef_solo working with Vagrant 1.8.4, so I suspect that issue is related to the first one. In other words,

    npm install express@3

works fine on the guest machine with Vagrant 1.8.4.

**Comment by samirgandhi19** [comment] 2016-08-03 17:31
Awesome! I went to vagrant 1.8.4 and vbox 5.0.x and all is well!

p.s. I don't care to understand the issue w/ 1.8.5 at this point.. the most important thing to me was being able to continue moving through the book and learning. Thank you for being so responsive

**Comment by gauravguptaster** [comment] 2016-08-04 08:20
Installing Vagrant 1.8.4 and and Virtual Box 5.0 solved the issue. Thanks!

**Comment by gauravguptaster** [comment] 2016-08-04 10:44
Cloudfoundry client is not being installed because the version of ruby is 1.9.3 and it needs atleast ruby > 2.0. I upgraded ruby and was able to install the client. I haven't had a chance to test it since I am still working through Chapter 7.

**Comment by semmypurewal** [comment] 2016-08-04 14:18
@gauravguptaster Thanks for the ruby info! Which package did you install to upgrade ruby? I can change the Vagrantfile to make it work.

**Comment by gauravguptaster** [comment] 2016-08-04 14:23
I used rvm 
https://rvm.io/rvm/install
**Steps**
Step 1.
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
Step 2.
\curl -sSL https://get.rvm.io | bash -s stable --ruby

**Comment by semmypurewal** [comment] 2016-08-12 13:53
Just to follow-up with everyone, I opened an issue with the Vagrant folks. It turns out they already have a fix for this, but it won't be out until the next release of Vagrant. So for now, the workaround is to use Vagrant 1.8.4 and VirtualBox 5.0.

**Comment by robertorr** [comment] 2017-07-20 22:50
I realize I'm a bit late to this party (over 3 years after the book was released!), but I'm running into the same problems trying to provision the VM with Vagrant.  I've tried the latest releases (VirtualBox 5.1.24 and Vagrant 1.9.7), and the releases recommended above (VirtualBox 5.0.40 and Vagrant 1.8.4), and I have the same problems with all of them.  I've tried the process on a Mac (OSX 10.12.6) and PC (Windows 7 SP1), but the result is the same.  Essentially, chef_solo fails with this error:

==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/nodejs/attributes/default.rb
==> default: ================================================================================
==> default: NoMethodError
==> default: -------------
==> default: undefined method `nodejs' for {}:Chef::Node::VividMash
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/nodejs/attributes/default.rb:20:in `from_file'
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/nodejs/attributes/default.rb:
==> default:  13:  # Unless required by applicable law or agreed to in writing, software
==> default:  14:  # distributed under the License is distributed on an "AS IS" BASIS,
==> default:  15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
==> default:  16:  # See the License for the specific language governing permissions and
==> default:  17:  # limitations under the License.
==> default:  18:  #
==> default:  19:
==> default:  20>> default.nodejs[:version] = "0.8.8"
==> default:  21:  default.nodejs[:from_source] = false
==> default:  22:  default.nodejs[:dir] = "/usr/local"
==> default:  23:  default.nodejs[:npm] = "1.0.10"
==> default:  24:
==> default:  25:

I then SSH into the VM and try to "provision" manually (using various 'apt-get' commands).  I am able to install nodejs and run the basic server, but when I try to install express ('npm install express@3'), I get the following error:

npm http GET https://registry.npmjs.org/express

npm ERR! Error: failed to fetch from registry: express
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:209:10)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at ClientRequest.onError (/usr/lib/nodejs/request/tunnel.js:164:21)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/vagrant/app/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "express@3"
npm ERR! cwd /home/vagrant/app
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: express
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/app/npm-debug.log
npm not ok

I've tried multiple ways of trying to get around this issue, but I am not a Vagrant, Chef, or Node/npm expert and I have not been successful (and it's getting frustrating!).  I really want to continue with the rest of the book (which is the most valuable part to me), but I'm hitting a wall.  Is there any way to solve these problems, or has the software "ecosystem" evolved to the point where the various package versions now have irreconcilable incompatibilities?

**Comment by avtomato** [comment] 2017-09-24 22:56
I am having the same issue.  VirtualBox 5.1.8 r111374 (Qt5.5.1) and Vagrant 1.9.5, PC Windows 7 SP1

==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/nodejs/attributes/default.rb
==> default: ================================================================================
==> default: NoMethodError
==> default: -------------
==> default: undefined method `nodejs' for {}:Chef::Node::VividMash
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/nodejs/attributes/default.rb:20:in `from_file'
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/nodejs/attributes/default.rb:
==> default:  13:  # Unless required by applicable law or agreed to in writing, software
==> default:  14:  # distributed under the License is distributed on an "AS IS" BASIS,
==> default:  15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
==> default:  16:  # See the License for the specific language governing permissions and
==> default:  17:  # limitations under the License.
==> default:  18:  #
==> default:  19:  
==> default:  20>> default.nodejs[:version] = "0.8.8"
==> default:  21:  default.nodejs[:from_source] = false
==> default:  22:  default.nodejs[:dir] = "/usr/local"
==> default:  23:  default.nodejs[:npm] = "1.0.10"
==> default:  24:  
==> default:  25:  
==> default: System Info:
==> default: ------------
==> default: chef_version=13.4.24
==> default: platform=ubuntu
==> default: platform_version=12.04
==> default: ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [i686-linux]
==> default: program_name=chef-solo worker: ppid=1690;start=22:42:49;
==> default: executable=/opt/chef/bin/chef-solo
==> default: Running handlers:
==> default: [2017-09-24T22:42:51+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-09-24T22:42:51+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 02 seconds
==> default: [2017-09-24T22:42:51+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-09-24T22:42:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-09-24T22:42:51+00:00] ERROR: undefined method `nodejs' for {}:Chef::Node::VividMash
==> default: [2017-09-24T22:42:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by arg4** [comment] 2017-09-25 03:03
@avtomato I'm also having the same issue. Using Debian 9 w/ virtualbox 5.1.26 and vagrant 1.9.1 I'll continue to work on this and see if I can figure out a fix.

**Comment by semmypurewal** [comment] 2018-02-04 01:33
Should be resolved now

**Closed by semmypurewal** 2018-02-04 01:33 UTC
